[project]
name = "api"
version = "0.1.0"
description = "Example API app depending on core"
requires-python = ">=3.12"
dependencies = [
    "core",
    "fastapi>=0.142.2",
    "uvicorn>=0.54.0",
]

[tool.uv.sources]
core = { workspace = true }

[project.scripts]
api = "api.main:main"

[build-system]
requires = ["uv_build>=0.9,<1"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "api"
