"""Files service: policy-checked writes, scope-aware reads, keyset listing.

Every function takes the ``store`` port and the bucket explicitly, so the
service holds no object-store global and tests inject ``FakeObjectStore``.
The row's ``tenant_id`` matches the ambient scope or the write runs inside
``tenant_scope(<row tenant>)``, so the flush guard always passes.
"""

from __future__ import annotations

import contextlib
import hashlib
import io
import uuid
from typing import BinaryIO, Protocol
from uuid import UUID

from crypto import tenant_scope
from sqlalchemy.orm import Session
from storage import ObjectStore

from api.authz import Principal
from api.config import get_config
from api.files.errors import (
    NotFound,
    ObjectMissing,
    PurposeNotAllowed,
    ScopeNotAllowed,
    TooLarge,
    UnsupportedType,
)
from api.files.lifecycle import detach_tenant, detach_user, discard
from api.files.policies import (
    SCOPE_TENANT,
    SCOPE_USER,
    Policy,
    check_mime,
    check_size,
    key_for,
    policy_for,
    sanitize_filename,
)
from api.files.reads import DEFAULT_PAGE, MAX_PAGE, InvalidCursor, get, list_page, open
from api.models import File, Role

__all__ = [
    "CHUNK_BYTES",
    "DEFAULT_PAGE",
    "MAX_PAGE",
    "InvalidCursor",
    "NotFound",
    "ObjectMissing",
    "PurposeNotAllowed",
    "ScopeNotAllowed",
    "TooLarge",
    "UnsupportedType",
    "delete",
    "detach_tenant",
    "detach_user",
    "get",
    "list_page",
    "open",
    "store_bytes",
    "store_upload",
]

CHUNK_BYTES = 64 * 1024


class Upload(Protocol):
    """Minimal seam over FastAPI's UploadFile: only the byte stream is read."""

    file: BinaryIO


def store_upload(
    session: Session,
    store: ObjectStore,
    *,
    bucket: str,
    tenant_id: str,
    user_id: int,
    purpose: str,
    scope: str = SCOPE_USER,
    filename: str,
    content_type: str,
    upload: Upload,
) -> File:
    """Store a browser upload: object first, then the row, then commit."""
    policy = _browser_policy(purpose, scope)
    if not check_mime(policy, content_type):
        raise UnsupportedType(content_type)
    sha256, size = _read_upload(upload.file, policy, cap=_upload_cap())
    file_id = uuid.uuid4()
    key = key_for(purpose, tenant_id, file_id)
    store.put(bucket, key, upload.file, content_type=content_type, size=size)
    row = _row(
        file_id=file_id,
        tenant_id=tenant_id,
        scope=scope,
        user_id=user_id,
        purpose=purpose,
        bucket=bucket,
        key=key,
        filename=sanitize_filename(filename),
        content_type=content_type,
        size=size,
        sha256=sha256,
    )
    _commit(session, store, row, key=key, tenant_id=tenant_id)
    return row


def store_bytes(
    session: Session,
    store: ObjectStore,
    *,
    bucket: str,
    tenant_id: str,
    user_id: int,
    purpose: str,
    filename: str,
    content_type: str,
    data: bytes,
    commit: bool = True,
) -> File:
    """Store server-generated bytes; the scope comes from the policy."""
    policy = policy_for(purpose)
    if policy is None:
        raise PurposeNotAllowed(purpose)
    if not check_mime(policy, content_type):
        raise UnsupportedType(content_type)
    size = len(data)
    cap = _upload_cap()
    if not check_size(policy, size, cap=cap):
        raise TooLarge(size, cap)
    file_id = uuid.uuid4()
    key = key_for(purpose, tenant_id, file_id)
    store.put(bucket, key, io.BytesIO(data), content_type=content_type, size=size)
    row = _row(
        file_id=file_id,
        tenant_id=tenant_id,
        scope=policy.server_scope,
        user_id=user_id,
        purpose=purpose,
        bucket=bucket,
        key=key,
        filename=sanitize_filename(filename),
        content_type=content_type,
        size=size,
        sha256=hashlib.sha256(data).hexdigest(),
    )
    if not commit:
        _flush(session, row, tenant_id)
        return row
    _commit(session, store, row, key=key, tenant_id=tenant_id)
    return row


def delete(session: Session, store: ObjectStore, file_id: UUID, *, principal: Principal) -> None:
    """Delete the row and commit, then drop the object best-effort."""
    row = session.get(File, file_id)
    if row is None or not _may_delete(row, principal):
        raise NotFound(file_id)
    bucket, key = row.bucket, row.object_key
    session.delete(row)
    session.commit()
    discard(store, bucket, key)


def _browser_policy(purpose: str, scope: str) -> Policy:
    policy = policy_for(purpose)
    if policy is None:
        raise PurposeNotAllowed(purpose)
    if scope not in policy.scopes:
        raise ScopeNotAllowed(scope)
    if not policy.browser_uploadable:
        raise PurposeNotAllowed(purpose)
    return policy


def _read_upload(stream: BinaryIO, policy: Policy, *, cap: int) -> tuple[str, int]:
    """Stream the upload: count bytes, refuse over cap, hash, then rewind."""
    digest = hashlib.sha256()
    size = 0
    while chunk := stream.read(CHUNK_BYTES):
        size += len(chunk)
        if not check_size(policy, size, cap=cap):
            raise TooLarge(size, cap)
        digest.update(chunk)
    stream.seek(0)
    return digest.hexdigest(), size


def _upload_cap() -> int:
    return get_config().storage.upload_max_bytes


def _row(
    *,
    file_id: UUID,
    tenant_id: str,
    scope: str,
    user_id: int,
    purpose: str,
    bucket: str,
    key: str,
    filename: str,
    content_type: str,
    size: int,
    sha256: str,
) -> File:
    return File(
        id=file_id,
        tenant_id=tenant_id,
        scope=scope,
        created_by_user_id=user_id,
        purpose=purpose,
        bucket=bucket,
        object_key=key,
        filename=filename,
        content_type=content_type,
        size_bytes=size,
        sha256=sha256,
    )


def _flush(session: Session, row: File, tenant_id: str) -> None:
    with tenant_scope(tenant_id):
        session.add(row)
        session.flush()


def _commit(session: Session, store: ObjectStore, row: File, *, key: str, tenant_id: str) -> None:
    """Flush and commit the row; a failed commit removes the orphan object."""
    try:
        _flush(session, row, tenant_id)
        session.commit()
    except BaseException:
        with contextlib.suppress(Exception):
            session.rollback()
        discard(store, row.bucket, key)
        raise


def _may_delete(row: File, principal: Principal) -> bool:
    if row.scope == SCOPE_USER:
        return row.created_by_user_id == principal.user_id
    if row.scope == SCOPE_TENANT:
        if row.created_by_user_id == principal.user_id:
            return True
        return row.tenant_id == principal.tenant_id and principal.has_role(Role.ADMIN)
    return False
